# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IfesTpzB1rQHEDxFOAWq23nxzF_Hzcxg
"""

pip install numpy pandas matplotlib seaborn scikit-learn tensorflow keras imbalanced-learn shap fastapi uvicorn

# =========================================
# 1️⃣ Import Required Libraries
# =========================================

import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.impute import SimpleImputer

# =========================================
# 2️⃣ Load Dataset
# =========================================

# Upload file in Colab first
from google.colab import files
uploaded = files.upload()

# Load dataset
df = pd.read_csv('/content/credit_card_fraud_10k (1).csv')

# View dataset
print("Dataset Shape:", df.shape)
df.head()

# =========================================
# DATA CLEANING
# =========================================

# Check missing values
print("Missing Values:\n", df.isnull().sum())

# Handle missing values (numerical)
num_cols = df.select_dtypes(include=np.number).columns

imputer = SimpleImputer(strategy='median')
df[num_cols] = imputer.fit_transform(df[num_cols])

# Remove duplicate rows
df = df.drop_duplicates()

print("Dataset shape after cleaning:", df.shape)

# =========================================
# FEATURE / TARGET SPLIT
# =========================================

target_column = 'is_fraud'   # fraud label

X = df.drop(columns=[target_column])
y = df[target_column]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

# =========================================
# TRAIN TEST SPLIT
# =========================================

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("Train Shape:", X_train.shape)
print("Test Shape:", X_test.shape)

# =========================================
# FEATURE SCALING
# =========================================

# Perform one-hot encoding for the 'merchant_category' column
X_train = pd.get_dummies(X_train, columns=['merchant_category'], drop_first=True)
X_test = pd.get_dummies(X_test, columns=['merchant_category'], drop_first=True)

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Scaling Completed")

# =========================================
# NORMALIZATION
# =========================================

normalizer = MinMaxScaler()

X_train_normalized = normalizer.fit_transform(X_train_scaled)
X_test_normalized = normalizer.transform(X_test_scaled)

print("Normalization Completed")

# =========================================
# CONVERT BACK TO DATAFRAME
# =========================================

X_train_final = pd.DataFrame(X_train_normalized, columns=X_train.columns)
X_test_final = pd.DataFrame(X_test_normalized, columns=X_test.columns)

print("Final Training Data Shape:", X_train_final.shape)
print("Final Test Data Shape:", X_test_final.shape)

X_train_final.head()

# ==========================================
#  Feature / Target Split
# ==========================================

target_column = 'is_fraud'   # fraud label column

X = df.drop(columns=[target_column])
y = df[target_column]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

from sklearn.model_selection import train_test_split

# ==========================================
# TRAIN SPLIT (70%)
# ==========================================

X_train, X_temp, y_train, y_temp = train_test_split(
    X,
    y,
    test_size=0.30,
    random_state=42,
    stratify=y
)

# ==========================================
# VALIDATION + TEST SPLIT (15% + 15%)
# ==========================================

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,
    random_state=42,
    stratify=y_temp
)

print("Training Set Shape:", X_train.shape)
print("Validation Set Shape:", X_val.shape)
print("Test Set Shape:", X_test.shape)

# ==========================================
# VALIDATION + TEST SPLIT
# ==========================================

from sklearn.model_selection import train_test_split

X_val, X_test, y_val, y_test = train_test_split(
    X_temp,
    y_temp,
    test_size=0.50,   # Split remaining data into 50% validation and 50% test
    random_state=42,
    stratify=y_temp   # Maintain fraud/non-fraud ratio
)

print("Validation Set Shape:", X_val.shape)
print("Test Set Shape:", X_test.shape)

print("\nValidation Class Distribution:")
print(y_val.value_counts())

print("\nTest Class Distribution:")
print(y_test.value_counts())

# ==========================================
# FINAL DATASET SUMMARY
# ==========================================

print("\n=========== FINAL DATASET SUMMARY ===========")

print("\nDataset Shapes")
print("Training Set:", X_train.shape)
print("Validation Set:", X_val.shape)
print("Test Set:", X_test.shape)

print("\nTotal Samples")
print("Train:", len(X_train))
print("Validation:", len(X_val))
print("Test:", len(X_test))

print("\nTarget Distribution")

print("\nTrain:")
print(y_train.value_counts())

print("\nValidation:")
print(y_val.value_counts())

print("\nTest:")
print(y_test.value_counts())

print("\n============================================")

# Install imbalanced-learn
!pip install imbalanced-learn

# ==========================================
# ORIGINAL TRAINING CLASS DISTRIBUTION
# ==========================================

print("\nOriginal Training Class Distribution")

print(y_train.value_counts())

print("\nPercentage Distribution")

print((y_train.value_counts(normalize=True) * 100).round(2))

from sklearn.preprocessing import LabelEncoder

# ==========================================
# Encode Categorical Columns
# ==========================================

label_encoders = {}

for col in df.columns:
    if df[col].dtype == 'object':   # check categorical columns
        le = LabelEncoder()
        df[col] = le.fit_transform(df[col].astype(str))
        label_encoders[col] = le

        print(f"{col} encoded successfully")

print("\nEncoding Completed")

# ==========================================
# 5. Split Features and Target
# ==========================================

target = "is_fraud"   # Define target column

# Split dataset
X = df.drop(columns=[target])
y = df[target]

print("Feature Shape:", X.shape)
print("Target Shape:", y.shape)

print("\nTarget Distribution:")
print(y.value_counts())

print("Before SMOTE")

print(y.value_counts())

# ==========================================
# BEFORE SMOTE DISTRIBUTION
# ==========================================

print("Before SMOTE\n")

print("Class Count:")
print(y.value_counts())

print("\nClass Percentage:")
print((y.value_counts(normalize=True) * 100).round(2))

from imblearn.over_sampling import SMOTE

# ==========================================
# 6. Apply SMOTE to balance the dataset
# ==========================================

sm = SMOTE(random_state=42)
X_resampled, y_resampled = sm.fit_resample(X, y)

print("After SMOTE")
print("Class Count:")
print(y_resampled.value_counts())

print("Class Percentage:")
print((y_resampled.value_counts(normalize=True) * 100).round(2))

# ==========================================
# 7. Create Final Synthetic Dataset
# ==========================================

synthetic_df = pd.concat(
    [pd.DataFrame(X_resampled, columns=X.columns),
     pd.DataFrame(y_resampled, columns=[target])],
    axis=1
)

# Convert all columns to integer
synthetic_df = synthetic_df.round().astype(int)

# Set transaction_id equal to row number
synthetic_df["transaction_id"] = range(1, len(synthetic_df) + 1)

# Move transaction_id to first column (optional but cleaner)
cols = ["transaction_id"] + [col for col in synthetic_df.columns if col != "transaction_id"]
synthetic_df = synthetic_df[cols]

print("New Dataset Shape:", synthetic_df.shape)

synthetic_df.head()

# Show last rows (mostly synthetic)

synthetic_df.tail(10)

synthetic_df.to_csv("fraud(3).csv", index=False)

# ==========================================
# Deep Learning Libraries
# ==========================================

import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, GRU, Dropout
from tensorflow.keras.callbacks import EarlyStopping

# ==========================================
# Apply SMOTE to Training Data and Scale Features
# ==========================================

from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler
import pandas as pd # Import pandas for get_dummies

# Perform one-hot encoding for the 'merchant_category' column
X_train_encoded = pd.get_dummies(X_train, columns=['merchant_category'], drop_first=True)
X_val_encoded = pd.get_dummies(X_val, columns=['merchant_category'], drop_first=True)
X_test_encoded = pd.get_dummies(X_test, columns=['merchant_category'], drop_first=True)

# Align columns - essential after one-hot encoding, especially if some categories
# are only present in train or test/val.
# Get all unique columns from encoded train, val, test
all_cols = X_train_encoded.columns.union(X_val_encoded.columns).union(X_test_encoded.columns)
X_train_encoded = X_train_encoded.reindex(columns=all_cols, fill_value=0)
X_val_encoded = X_val_encoded.reindex(columns=all_cols, fill_value=0)
X_test_encoded = X_test_encoded.reindex(columns=all_cols, fill_value=0)


# Apply SMOTE to the training data
sm = SMOTE(random_state=42)
X_train_smote, y_train_smote = sm.fit_resample(X_train_encoded, y_train)

print("Shape of X_train after SMOTE:", X_train_smote.shape)
print("Shape of y_train after SMOTE:", y_train_smote.shape)
print("Class distribution after SMOTE:\n", y_train_smote.value_counts())

# Scale the features
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train_smote)
X_val_scaled = scaler.transform(X_val_encoded)
X_test_scaled = scaler.transform(X_test_encoded)

# ==========================================
# Convert to numpy arrays with explicit float dtype
# ==========================================

X_train_dl = np.array(X_train_scaled).astype(np.float32)
y_train_dl = np.array(y_train_smote).astype(np.float32)

X_val_dl = np.array(X_val_scaled).astype(np.float32)
y_val_dl = np.array(y_val).astype(np.float32)

X_test_dl = np.array(X_test_scaled).astype(np.float32)
y_test_dl = np.array(y_test).astype(np.float32)

print("Train Shape (DL):", X_train_dl.shape)
print("Validation Shape (DL):", X_val_dl.shape)
print("Test Shape (DL):", X_test_dl.shape)

# ==========================================
# MLP MODEL (~20K PARAMETERS)
# ==========================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, BatchNormalization

mlp = Sequential([

    Dense(96, activation='relu', input_shape=(X_train_dl.shape[1],)),
    BatchNormalization(),
    Dropout(0.3),

    Dense(48, activation='relu'),
    BatchNormalization(),
    Dropout(0.3),

    Dense(24, activation='relu'),
    Dropout(0.2),

    Dense(12, activation='relu'),

    Dense(1, activation='sigmoid')
])

mlp.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

mlp.summary()

history_mlp = mlp.fit(
    X_train_dl,
    y_train_dl,
    validation_data=(X_val_dl, y_val_dl),
    epochs=5,
    batch_size=32,
    verbose=1
)

# ==========================================
# Reshape for LSTM / GRU
# ==========================================

# Convert 2D data into 3D sequence format
X_train_seq = X_train_dl.reshape((X_train_dl.shape[0], 1, X_train_dl.shape[1]))
X_val_seq = X_val_dl.reshape((X_val_dl.shape[0], 1, X_val_dl.shape[1]))
X_test_seq = X_test_dl.reshape((X_test_dl.shape[0], 1, X_test_dl.shape[1]))

print("Train Sequence Shape:", X_train_seq.shape)
print("Validation Sequence Shape:", X_val_seq.shape)
print("Test Sequence Shape:", X_test_seq.shape)

# ==========================================
# LSTM MODEL (~20K PARAMETERS)
# ==========================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, BatchNormalization

lstm = Sequential([

    LSTM(32, return_sequences=True, input_shape=(1, X_train_dl.shape[1])),
    BatchNormalization(),
    Dropout(0.3),

    LSTM(16),
    BatchNormalization(),
    Dropout(0.3),

    Dense(16, activation='relu'),
    Dropout(0.2),

    Dense(1, activation='sigmoid')
])

lstm.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

lstm.summary()

from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import ReduceLROnPlateau

early_stop = EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor='val_loss',
    factor=0.7,
    patience=3,
    min_lr=0.00001
)

history_lstm = lstm.fit(
    X_train_seq,
    y_train_dl,
    validation_data=(X_val_seq, y_val_dl),
    epochs=5,
    batch_size=16,
    callbacks=[early_stop, reduce_lr],
    verbose=1
)

# ==========================================
# IMPROVED GRU MODEL
# ==========================================

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GRU, Dense, Dropout, BatchNormalization

gru = Sequential([

    GRU(128, return_sequences=True, input_shape=(1, X_train_dl.shape[1])),
    BatchNormalization(),
    Dropout(0.3),

    GRU(64),
    BatchNormalization(),
    Dropout(0.3),

    Dense(32, activation='relu'),
    Dropout(0.2),

    Dense(1, activation='sigmoid')
])

gru.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

gru.summary()

history_gru = gru.fit(
    X_train_seq,
    y_train_dl,
    validation_data=(X_val_seq, y_val_dl),
    epochs=5,
    batch_size=32,
    callbacks=[early_stop],
    verbose=1
)

# ==========================================
# Predictions
# ==========================================

mlp_pred = mlp.predict(X_test_dl).ravel()
lstm_pred = lstm.predict(X_test_seq).ravel()
gru_pred = gru.predict(X_test_seq).ravel()

# ==========================================
# Ensemble Model
# ==========================================

ensemble_pred = (mlp_pred + lstm_pred + gru_pred) / 3

y_pred = (ensemble_pred > 0.5).astype(int)

from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score

print("Accuracy:", accuracy_score(y_test_dl, y_pred))
print("Precision:", precision_score(y_test_dl, y_pred))
print("Recall:", recall_score(y_test_dl, y_pred))
print("ROC AUC:", roc_auc_score(y_test_dl, ensemble_pred))

from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score

# ==========================================
# Model Evaluation Function
# ==========================================

def evaluate_model(y_true, y_pred, y_prob):

    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred)
    recall = recall_score(y_true, y_pred)
    f1 = f1_score(y_true, y_pred)
    roc_auc = roc_auc_score(y_true, y_prob)

    return accuracy, precision, recall, f1, roc_auc

# ==========================================
# Evaluate Models
# ==========================================

# Convert probabilities to binary class predictions
mlp_class = (mlp_pred > 0.5).astype(int)
lstm_class = (lstm_pred > 0.5).astype(int)
gru_class = (gru_pred > 0.5).astype(int)
ensemble_class = (ensemble_pred > 0.5).astype(int)

mlp_metrics = evaluate_model(y_test_dl, mlp_class, mlp_pred)
lstm_metrics = evaluate_model(y_test_dl, lstm_class, lstm_pred)
gru_metrics = evaluate_model(y_test_dl, gru_class, gru_pred)
ensemble_metrics = evaluate_model(y_test_dl, ensemble_class, ensemble_pred)

# ==========================================
# Model Comparison Table
# ==========================================

import pandas as pd

results = pd.DataFrame({

    "Model": ["MLP", "LSTM", "GRU", "Ensemble"],

    "Accuracy": [
        mlp_metrics[0],
        lstm_metrics[0],
        gru_metrics[0],
        ensemble_metrics[0]
    ],

    "Precision": [
        mlp_metrics[1],
        lstm_metrics[1],
        gru_metrics[1],
        ensemble_metrics[1]
    ],

    "Recall": [
        mlp_metrics[2],
        lstm_metrics[2],
        gru_metrics[2],
        ensemble_metrics[2]
    ],

    "F1 Score": [
        mlp_metrics[3],
        lstm_metrics[3],
        gru_metrics[3],
        ensemble_metrics[3]
    ],

    "ROC-AUC": [
        mlp_metrics[4],
        lstm_metrics[4],
        gru_metrics[4],
        ensemble_metrics[4]
    ]

})

results

# ==========================================
# Select Best Model based on ROC-AUC
# ==========================================

best_model = results.loc[results["ROC-AUC"].idxmax()]

print("Best Model Selected:")
print(best_model)

import matplotlib.pyplot as plt

results.set_index("Model")[["Accuracy","F1 Score","ROC-AUC"]].plot(
    kind="bar",
    figsize=(8,5)
)

plt.title("Model Performance Comparison")
plt.ylabel("Score")
plt.show()

# ==========================================
# FRAUD PREDICTION FUNCTION
# ==========================================

def predict_transaction(transaction):

    # Ensure transaction is a DataFrame
    if not isinstance(transaction, pd.DataFrame):
        transaction = pd.DataFrame([transaction])

    # The input 'transaction' (e.g., from X_test) is already one-hot encoded and aligned
    # No need to call pd.get_dummies or reindex here if X_test is already prepared.
    # We'll assume 'transaction' is already in the correct format for scaling.
    transaction_aligned = transaction # Directly use the transaction as it's already prepared

    # Scale transaction
    transaction_scaled = scaler.transform(transaction_aligned)

    # Convert to DL format
    transaction_dl = transaction_scaled.reshape(1, -1)
    transaction_seq = transaction_scaled.reshape(1,1,-1)

    # Model predictions
    mlp_p = mlp.predict(transaction_dl)[0][0]
    lstm_p = lstm.predict(transaction_seq)[0][0]
    gru_p = gru.predict(transaction_seq)[0][0]

    # Ensemble prediction
    final_score = (mlp_p + lstm_p + gru_p) / 3

    if final_score > 0.5:
        result = "Fraudulent Transaction"
    else:
        result = "Legitimate Transaction"

    return result, final_score

# ==========================================
# Fraud Prediction Function
# ==========================================

def predict_transaction(transaction):

    # Ensure transaction is a DataFrame
    if not isinstance(transaction, pd.DataFrame):
        transaction = pd.DataFrame([transaction])

    # Perform one-hot encoding for the 'merchant_category' column
    transaction_encoded = pd.get_dummies(transaction, columns=['merchant_category'], drop_first=True)

    # Align columns with the training data (assuming 'all_cols' from GnodNjSbnxiA is available)
    # If 'all_cols' is not globally available, it needs to be passed or re-derived.
    # For this fix, we assume 'all_cols' from GnodNjSbnxiA is still in scope.
    global all_cols # Ensure all_cols is accessible
    transaction_aligned = transaction_encoded.reindex(columns=all_cols, fill_value=0)

    # Scale the features using the previously fitted scaler
    transaction_scaled = scaler.transform(transaction_aligned)

    # Convert to numpy arrays with explicit float dtype for DL models
    data = transaction_scaled.astype("float32")

    # For MLP
    mlp_prob = mlp.predict(data)[0][0]

    # For LSTM / GRU reshape
    data_seq = data.reshape(data.shape[0], 1, data.shape[1])

    lstm_prob = lstm.predict(data_seq)[0][0]
    gru_prob = gru.predict(data_seq)[0][0]

    # Ensemble probability
    risk_score = (mlp_prob + lstm_prob + gru_prob) / 3

    # Final prediction
    if risk_score > 0.5:
        prediction = "Fraudulent Transaction"
    else:
        prediction = "Legitimate Transaction"

    return prediction, risk_score

sample = pd.DataFrame({
    "transaction_amount":[500],
    "card_present":[0],
    "device_trusted":[0],
    "merchant_category":["electronics"]
})

prediction, risk_score = predict_transaction(sample)

print(prediction)
print(risk_score)

# ==========================================
# CHECK MULTIPLE TRANSACTIONS
# ==========================================

for i in range(5):

    tx = X_test.iloc[[i]]

    pred, score = predict_transaction(tx)

    print("Transaction",i)
    print("Result:",pred)
    print("Risk Score:",round(score,3))
    print("------------------")

# ==========================================
# FRAUD DETECTION + ALERT SYSTEM
# ==========================================

def fraud_detection_system(transaction, amount, location):

    # Ensure transaction is a DataFrame
    if not isinstance(transaction, pd.DataFrame):
        transaction = pd.DataFrame([transaction])

    # Perform one-hot encoding for the 'merchant_category' column
    transaction_encoded = pd.get_dummies(transaction, columns=['merchant_category'], drop_first=True)

    # Align columns with the training data (assuming 'all_cols' from GnodNjSbnxiA is available)
    global all_cols # Ensure all_cols is accessible
    transaction_aligned = transaction_encoded.reindex(columns=all_cols, fill_value=0)

    # Scale the features using the previously fitted scaler
    transaction_scaled = scaler.transform(transaction_aligned)

    # Convert to numpy arrays with explicit float dtype for DL models
    transaction_np = transaction_scaled.astype("float32")

    # Prepare input formats
    transaction_dl = transaction_np.reshape(1, -1)
    transaction_seq = transaction_np.reshape(1, 1, -1)

    # Model predictions
    mlp_prob = mlp.predict(transaction_dl, verbose=0)[0][0]
    lstm_prob = lstm.predict(transaction_seq, verbose=0)[0][0]
    gru_prob = gru.predict(transaction_seq, verbose=0)[0][0]

    # Ensemble fraud score
    fraud_score = (mlp_prob + lstm_prob + gru_prob) / 3

    # Decision system
    if fraud_score >= 0.5:

        result = "Fraudulent Transaction"

        print("\n⚠️ FRAUD ALERT ⚠️")
        print("----------------------------")
        print("Transaction Status:", result)
        print(f"Unusual transaction of ₹{amount} detected at {location}")
        print("Fraud Risk Score:", round(fraud_score,3))
        print("Recommended Action: Block card immediately")

    else:

        result = "Legitimate Transaction"

        print("\n✅ Transaction Approved")
        print("----------------------------")
        print("Transaction Status:", result)
        print(f"Amount: ₹{amount}")
        print("Location:", location)
        print("Fraud Risk Score:", round(fraud_score,3))

    return result, fraud_score

# Take a sample transaction
sample_tx = X_test.iloc[[0]]

fraud_detection_system(
    transaction = sample_tx,
    amount = sample_tx['amount'].values[0],
    location = "International Transaction"
)

# ==========================================

# AI FRAUD TRANSACTION CHECKER (FINAL FIXED)

# ==========================================

import pandas as pd
import numpy as np
import base64
from IPython.display import display, Javascript

# Load dataset

df = pd.read_csv("/content/fraud(3).csv")

print("🔍 AI Fraud Transaction Checker")

# Ask user for Transaction ID

tid = int(input("Enter Transaction ID: "))

# Search transaction

transaction = df[df["transaction_id"] == tid]

if transaction.empty:

    print("❌ Transaction ID not found!")

else:

    row = transaction.iloc[0]

    print("\n=========== Transaction Details ===========\n")

    for column in df.columns:
        print(f"{column:<25} : {row[column]}")

    print("\n===========================================\n")

    # --------------------------------------
    # Prepare features
    # --------------------------------------

    features = transaction.drop(columns=["is_fraud"], errors="ignore").copy()

    # Extract merchant category value
    cat_value = int(features["merchant_category"].values[0])

    # Remove original column
    features = features.drop(columns=["merchant_category"])

    # Create expected one-hot columns
    features["merchant_category_Electronics"] = 0
    features["merchant_category_Food"] = 0
    features["merchant_category_Grocery"] = 0
    features["merchant_category_Travel"] = 0

    # Map numeric category to one-hot
    if cat_value == 0:
        features["merchant_category_Electronics"] = 1
    elif cat_value == 1:
        features["merchant_category_Food"] = 1
    elif cat_value == 2:
        features["merchant_category_Grocery"] = 1
    elif cat_value == 3:
        features["merchant_category_Travel"] = 1

    # Ensure same column order as training (use all_cols from GnodNjSbnxiA)
    global all_cols # Ensure all_cols is accessible
    features = features.reindex(columns=all_cols, fill_value=0)

    # Scale features
    features_scaled = scaler.transform(features)

    # Convert to numpy
    features_np = features_scaled.astype("float32")

    # Prepare inputs
    features_dl = features_np.reshape(1, -1)
    features_seq = features_np.reshape(1, 1, -1)

    # --------------------------------------
    # Model predictions
    # --------------------------------------

    mlp_prob = mlp.predict(features_dl, verbose=0)[0][0]
    lstm_prob = lstm.predict(features_seq, verbose=0)[0][0]
    gru_prob = gru.predict(features_seq, verbose=0)[0][0]

    fraud_score = (mlp_prob + lstm_prob + gru_prob) / 3

    print("🤖 AI Fraud Risk Score:", round(fraud_score,3))

    # --------------------------------------
    # Fraud decision
    # --------------------------------------

    if fraud_score < 0.5:

        print("\n✅ LEGITIMATE TRANSACTION")

    else:

        print("\n🚨 FRAUD ALERT 🚨")
        print("⚠️ Fraudulent Transaction Detected!")
        print("Recommended Action: Block Card Immediately")

        # Alarm sound
        try:
            with open("/content/jeremayjimenez-pakistan-eas-alarm-2005-496801.mp3", "rb") as f:
                data_uri = "data:audio/mp3;base64," + base64.b64encode(f.read()).decode()

            display(Javascript(f"""
            var audio = new Audio("{data_uri}");
            audio.play();
            """))

        except:
            print("🔊 Alarm file not found")

import matplotlib.pyplot as plt

x = [1, 2, 3, 4]
y = [10, 20, 15, 25]

plt.plot(x, y)
plt.title("Line Graph")
plt.xlabel("X Axis")
plt.ylabel("Y Axis")
plt.show()

import matplotlib.pyplot as plt

df['is_fraud'].value_counts().plot(kind='bar')
plt.title("Fraud vs Non-Fraud")
plt.xlabel("Class")
plt.ylabel("Count")
plt.show()

plt.hist(df['amount'], bins=10)
plt.title("Transaction Amount Distribution")
plt.xlabel("Amount")
plt.ylabel("Frequency")
plt.show()

plt.scatter(df['amount'], df['cardholder_age'])
plt.title("Amount vs Age")
plt.xlabel("Amount")
plt.ylabel("Age")
plt.show()

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

y_true = y_test_dl
y_pred = ensemble_class   # Using the pre-calculated ensemble predictions

cm = confusion_matrix(y_true, y_pred)

disp = ConfusionMatrixDisplay(confusion_matrix=cm)
disp.plot()
plt.title("Confusion Matrix")
plt.show()

from sklearn.metrics import accuracy_score

acc = accuracy_score(y_true, y_pred)
print("Accuracy:", acc)

from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred))

from sklearn.metrics import roc_curve, auc

y_prob = ensemble_pred

fpr, tpr, _ = roc_curve(y_true, y_prob)
roc_auc = auc(fpr, tpr)

plt.plot(fpr, tpr)
plt.title("ROC Curve")
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.show()

from sklearn.metrics import precision_recall_curve

precision, recall, _ = precision_recall_curve(y_true, y_prob)

plt.plot(recall, precision)
plt.title("Precision-Recall Curve")
plt.xlabel("Recall")
plt.ylabel("Precision")
plt.show()

from sklearn.ensemble import RandomForestClassifier



# 3. Split data
X = df.drop('is_fraud', axis=1)
y = df['is_fraud']

# 4. Create and train model (IMPORTANT)
model = RandomForestClassifier()
model.fit(X, y)

# 5. Feature Importance Graph
importance = model.feature_importances_
features = X.columns

plt.barh(features, importance)
plt.title("Feature Importance")
plt.xlabel("Importance")
plt.show()

plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
plt.plot(history_mlp.history['loss'], label='Training Loss')
plt.plot(history_mlp.history['val_loss'], label='Validation Loss')
plt.title("MLP Model Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend()

plt.subplot(1, 2, 2)
plt.plot(history_mlp.history['accuracy'], label='Training Accuracy')
plt.plot(history_mlp.history['val_accuracy'], label='Validation Accuracy')
plt.title("MLP Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend()

plt.tight_layout()
plt.show()

# ==============================
# 📦 INSTALL (RUN ONLY ONCE)
# ==============================
!pip install gradio pandas numpy plotly gtts huggingface_hub

# ==============================
# 📦 IMPORTS
# ==============================
import gradio as gr
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from gtts import gTTS
from huggingface_hub import InferenceClient
import uuid
import base64

# ==============================
# 🔑 API
# ==============================
hf_client = InferenceClient(
    token="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"
)

# ==============================
# 📂 DATA
# ==============================
DATA_PATH = "/content/fraud(3).csv"

try:
    df = pd.read_csv(DATA_PATH)
except:
    df = pd.DataFrame()

# ==============================
# 🔊 CLEAN VOICE
# ==============================
def speak(text):
    clean_text = text.replace("🚨", "").replace("✅", "").replace("⚠️", "").replace("💡", "")

    file_path = f"/tmp/audio_{uuid.uuid4().hex}.mp3"
    tts = gTTS(text=clean_text, lang='en')
    tts.save(file_path)

    with open(file_path, "rb") as f:
        audio_bytes = f.read()
        audio_base64 = base64.b64encode(audio_bytes).decode()

    return f"""
    <audio autoplay>
        <source src="data:audio/mp3;base64,{audio_base64}" type="audio/mp3">
    </audio>
    """

# ==============================
# 🧠 FRAUD ENGINE (UNCHANGED)
# ==============================
def fraud_engine(row):
    score = 0
    reasons = []

    if row.get("foreign_transaction", 0) == 1:
        score += 25
        reasons.append("Foreign transaction")

    if row.get("location_mismatch", 0) == 1:
        score += 25
        reasons.append("Location mismatch")

    if row.get("velocity_last_24h", 0) > 5:
        score += 20
        reasons.append("High transaction velocity")

    if row.get("device_trust_score", 1) < 0.5:
        score += 30
        reasons.append("Low device trust")

    prob = min(score, 100)
    is_fraud = int(row.get("is_fraud", 0))

    status = "🚨 FRAUD DETECTED" if is_fraud == 1 else "✅ SAFE TRANSACTION"

    return prob, status, reasons, is_fraud

# ==============================
# 📊 GAUGE (UNCHANGED)
# ==============================
def create_gauge(prob):
    return go.Figure(go.Indicator(
        mode="gauge+number",
        value=prob,
        title={'text': "Fraud Probability"},
        gauge={'axis': {'range': [0, 100]}}
    ))

# ==============================
# 🧾 ANALYZE (UNCHANGED)
# ==============================
def analyze_transaction(tid):
    global df

    try:
        row = df[df["transaction_id"] == int(tid)]
    except:
        msg = "Invalid Transaction ID"
        return msg, None, None, speak(msg)

    if row.empty:
        msg = "Transaction not found"
        return msg, None, None, speak(msg)

    row = row.iloc[0].fillna(0).to_dict()

    prob, status, reasons, is_fraud = fraud_engine(row)

    display_text = f"""
=============================
🔎 TRANSACTION DETAILS
=============================
Transaction ID : {row.get('transaction_id')}
Amount         : {row.get('amount', 'N/A')}

-----------------------------
🧠 AI RESULT
-----------------------------
Status            : {status}
Fraud Probability : {prob}%
Dataset Label     : {"Fraud" if is_fraud == 1 else "Safe"}

-----------------------------
⚠️ RISK FACTORS
-----------------------------
{' | '.join(reasons) if reasons else 'Low Risk'}

-----------------------------
💡 RECOMMENDATION
-----------------------------
{"Block transaction immediately!" if is_fraud == 1 else "Transaction is safe"}
"""

    voice_text = f"""
Transaction {row.get('transaction_id')} analysis.
Status is {'fraud detected' if is_fraud == 1 else 'safe transaction'}.
Fraud probability is {prob} percent.
{'Warning. Risk factors include ' + ', '.join(reasons) if reasons else 'No major risks detected.'}
"""

    return display_text, create_gauge(prob), pd.DataFrame([row]), speak(voice_text)

# ==============================
# 📊 ANALYTICS (UNCHANGED)
# ==============================
def analytics():
    global df

    df["is_fraud"] = df["is_fraud"].fillna(0)

    total = len(df)
    fraud = int(df["is_fraud"].sum())

    fig = go.Figure(data=[
        go.Pie(labels=["Safe", "Fraud"],
               values=[total - fraud, fraud])
    ])

    voice = f"Total transactions {total}. Fraud cases {fraud}."
    return total, fraud, fig, speak(voice)

# ==============================
# ➕ ADD TRANSACTION (UNCHANGED)
# ==============================
def add_transaction(foreign, location, velocity, device, is_fraud):
    global df

    new_id = int(df["transaction_id"].max()) + 1 if not df.empty else 1

    new_row = {
        "transaction_id": new_id,
        "foreign_transaction": int(foreign),
        "location_mismatch": int(location),
        "velocity_last_24h": float(velocity),
        "device_trust_score": float(device),
        "is_fraud": int(is_fraud)
    }

    df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)
    df.to_csv(DATA_PATH, index=False)

    msg = f"Transaction {new_id} added successfully"
    return df.tail(10), speak(msg)

# ==============================
# 🤖 CHATBOT (UNCHANGED)
# ==============================
def chatbot(q):
    try:
        res = hf_client.text_generation(
            prompt=q,
            model="google/flan-t5-large",
            max_new_tokens=100
        )
    except:
        res = "AI service unavailable"

    return res, speak(res)

# ==============================
# 🎨 NEW UI DESIGN (LIGHT + 3D)
# ==============================
custom_css = """
body {
    background: linear-gradient(135deg,#e3f2fd,#ffffff);
}

.gradio-container {
    font-family: 'Segoe UI', sans-serif;
}

/* Cards */
.gr-box {
    border-radius: 20px !important;
    box-shadow: 0 10px 30px rgba(0,0,0,0.1);
    transition: 0.3s;
}

.gr-box:hover {
    transform: translateY(-5px);
}

/* Buttons */
button {
    background: linear-gradient(135deg,#4facfe,#00f2fe) !important;
    color: white !important;
    border-radius: 12px !important;
    font-weight: bold;
}

/* Input */
input, textarea {
    border-radius: 10px !important;
}

/* CREDIT CARD CURSOR */
body {
    cursor: url('https://cdn-icons-png.flaticon.com/512/633/633611.png'), auto;
}
"""

# ==============================
# 🎨 UI (UPDATED ONLY STYLE)
# ==============================
with gr.Blocks(css=custom_css) as app:

    gr.Markdown("""
    <h1 style='text-align:center;
               background:linear-gradient(90deg,#4facfe,#00f2fe);
               -webkit-background-clip:text;
               color:transparent;
               font-size:40px;'>
    🚀 PLUTO AI SYSTEM
    </h1>
    """)

    with gr.Tabs():

        with gr.Tab("Detection"):
            tid = gr.Textbox(label="Transaction ID")
            btn = gr.Button("Analyze")

            out = gr.Textbox(label="AI Report", lines=20)
            gauge = gr.Plot()
            table = gr.Dataframe()
            audio = gr.HTML()

            btn.click(analyze_transaction,
                      inputs=tid,
                      outputs=[out, gauge, table, audio])

        with gr.Tab("Analytics"):
            total = gr.Number(label="Total Transactions")
            fraud = gr.Number(label="Fraud Count")
            chart = gr.Plot()
            audio2 = gr.HTML()

            gr.Button("Load Analytics").click(
                analytics,
                outputs=[total, fraud, chart, audio2]
            )

        with gr.Tab("Add Transaction"):
            f = gr.Textbox(label="foreign_transaction")
            l = gr.Textbox(label="location_mismatch")
            v = gr.Textbox(label="velocity_last_24h")
            d = gr.Textbox(label="device_trust_score")
            i = gr.Textbox(label="is_fraud")

            btn2 = gr.Button("Add Transaction")

            table2 = gr.Dataframe()
            audio3 = gr.HTML()

            btn2.click(add_transaction,
                       inputs=[f, l, v, d, i],
                       outputs=[table2, audio3])

        with gr.Tab("AI Assistant"):
            q = gr.Textbox(label="Ask PLUTO")
            btn3 = gr.Button("Ask")

            ans = gr.Textbox(lines=6)
            audio4 = gr.HTML()

            btn3.click(chatbot,
                       inputs=q,
                       outputs=[ans, audio4])

# ==============================
# ▶️ RUN
# ==============================
app.launch(debug=True)